### PR TITLE
Handle recursive Sexps in Sexp#inspect

### PR DESCRIPTION
**Pull request by presidentbeef**
What do you think about this? On one hand it matches Array behavior and prevents infinite recursion. On the other hand it may mask implementation errors.

### CODE REVIEW

**Comment by zenspider** [comment]
May I ask why?

You'll never get such a construct from ruby_parser... What kind of black magic are you dealing with? :P

**Comment by presidentbeef** [comment]
Yeah, that's why I'm unsure if you want it in the general library. I'm not really sure how I'm ending up in this state (haven't been able to repro on my own, but this code "fixed" an issue for a user. Maybe it's a bad thing to cover it up. I'm probably going to add it to Brakeman, at least temporarily.

Just throwing it out there.

**Comment by zenspider** [comment]
I'm not sure about this one. If this is happening in the wild, I'd really like to see a repro because it is probably a bug in our code somewhere (probably on me). It shouldn't be happening at all.

**Comment by presidentbeef** [comment]
It happened with real code but I'm not sure I ever had access to it. I'll look again.

**Comment by zenspider** [comment]
> On Jan 21, 2016, at 16:47, Justin <notifications@github.com> wrote:
> 
> It happened with real code but I'm not sure I ever had access to it. I'll look again.

Hrm... I haven't run a gauntlet in a while... and all I do is parse, I don't inspect. I can change my gauntlet to do that and see if I find it. I doubt I will tho.

**Comment by zenspider** [comment]
Closing until we have a repro/need.

**Pull request closed without merging**
